server:
  port: 8080
spring:
  profiles:
    active: druid
  thymeleaf:
    cache: false
    mode: HTML
  freemarker:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
security:
  basic:
    enabled: false
# how often to trigger the timer
timer:
  period: '2000'