server:
  port: 8082
spring:
  application:
    name: res
security:
  oauth2:
    client:
      client_id: client
      client-secret: 123456
    resource:
      token-info-uri: http://localhost:8081/oauth/check_token
      user-info-uri: http://localhost:8081/user/profile
#      jwt:
#        key-value: |
#          -----BEGIN PUBLIC KEY-----
#          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApxxRlUTx3WsodgBl3fxh
#          RkfxsKkEIwhqdJa2ix3HZdoYvOiXOEBcZBdBYzgzscCKcFvnnUx6Fmm5eJ4/IqK1
#          wRyM8kauh1lD3y84x99+78HQJwNEpvTa8tlfqohERA9YD0SOqme9RO0vF7mMiuqX
#          B3UaNzALlJBPcKUwiELbkQF3MzPnYSBEWES5efZsBJQlAPTGTKYI3bS9r4SnJUoc
#          P6F82eJXhVn9pSJz/8kGaefG6OCYAaPztJYTZmebq7PZHwMoK8Zu9ADYZIMRsDpP
#          ZG7sBtPQsWAof4q+DFwSuSWpssVkNWtB+MUjXauRtxhfqx4cO3kH96BBJ8BNySMy
#          RQIDAQAB
#          -----END PUBLIC KEY-----
eureka:
  client:
    serviceUrl:
      defaultZone: http://jackie:123456@alpha-eureka-01:8761/eureka/,http://jackie:123456@alpha-eureka-02:8762/eureka/,http://jackie:123456@alpha-eureka-03:8763/eureka/