version: '2'
services:
  mysqlmaster:
    image: mysql:5.7.15
    container_name: "mysql_master1"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - "./data/mysql-master:/var/lib/mysql/"
      - "./config/mysql-master:/etc/mysql/conf.d/"
    ports:
      - "3306:3306"
  mysqlslave:
    image: mysql:5.7.15
    container_name: "mysql_slave1"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - "./data/mysql-slave:/var/lib/mysql/"
      - "./config/mysql-slave:/etc/mysql/conf.d/"
    ports:
      - "3307:3306"
  mysqlconfigure:
    image: mysql:5.7.15
    container_name: "mysql_configure"
    environment:
      - "MYSQL_SLAVE_PASSWORD=root"
      - "MYSQL_MASTER_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_REPLICATION_USER=repl"
      - "MYSQL_REPLICATION_PASSWORD=repl"
    volumes:
      - "./mysql_connector.sh:/tmp/mysql_connector.sh"
    command: /bin/bash -x /tmp/mysql_connector.sh
