# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:8080/oauth/token?grant_type=client_credentials&scope=read
Authorization: Basic Y2xpZW50OjEyMzQ1Ng==

###

POST http://localhost:8080/oauth/token?grant_type=password&scope=read&username=user&password=123456
Authorization: Basic Y2xpZW50OjEyMzQ1Ng==

###

POST http://localhost:8080/oauth/authorize?response_type=token&client_id=client&redirect_uri=https://www.baidu.com

###

GET http://localhost:8080/user/profile
Authorization: bearer 41a482b7-238c-461d-be52-b3350e19392c

###

GET http://localhost:8080/product/1
Authorization: bearer 41a482b7-238c-461d-be52-b3350e19392c

###

GET http://localhost:8080/oauth/check_token?token=41a482b7-238c-461d-be52-b3350e19392c
Authorization: Basic Y2xpZW50OjEyMzQ1Ng==

###

GET http://localhost:8080/oauth/authorize?response_type=code&client_id=client&scope=read&redirect_uri=https://www.baidu.com

###

POST http://localhost:8080/oauth/token?grant_type=authorization_code&code=8Efcrb&redirect_uri=https://www.baidu.com&scope=read
Authorization: Basic Y2xpZW50OjEyMzQ1Ng==

###

GET http://localhost:8081
Authorization: bearer b1e6db89-cd3a-4205-a2d1-a515209a7435

###

GET http://192.168.200.19:8929/rest/front/admin/doc/index?params={"name":"人脸","pageNo":1,"pageSize":20}

###