# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:8080/oauth/token?grant_type=client_credentials&scope=read
Authorization: Basic Y2xpZW50OjEyMzQ1Ng==

###

POST http://localhost:8080/oauth/token?grant_type=password&scope=read&username=user&password=123456
Authorization: Basic Y2xpZW50OjEyMzQ1Ng==

###

POST http://localhost:8080/oauth/authorize?response_type=token&client_id=client&redirect_uri=https://www.baidu.com

###

GET http://localhost:8080/user/profile
Authorization: bearer 88f244f1-1575-450c-8927-9e6c2e0bcbdf

###

GET http://localhost:8080/product/1
Authorization: bearer d07ea6d7-1539-4f09-bee6-9a3103367342

###

GET http://localhost:8080/oauth/check_token?token=f5963bbe-e4c7-4e9f-8f78-bc78e72ae508
Authorization: Basic Y2xpZW50OjEyMzQ1Ng==

###

GET http://localhost:8080/oauth/authorize?response_type=code&client_id=client&scope=read&redirect_uri=https://www.baidu.com

###

POST http://localhost:8080/oauth/token?grant_type=authorization_code&code=8Efcrb&redirect_uri=https://www.baidu.com&scope=read
Authorization: Basic Y2xpZW50OjEyMzQ1Ng==

###

GET http://localhost:8081
Authorization: bearer b1e6db89-cd3a-4205-a2d1-a515209a7435

###