# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:8080/oauth/token?grant_type=client_credentials&scope=read
Authorization: Basic Y2xpZW50OjEyMzQ1Ng==

###

POST http://localhost:8080/oauth/token?grant_type=sms_code&scope=read&username=user&password=123456
Authorization: Basic Y2xpZW50OjEyMzQ1Ng==

###

POST http://localhost:8080/oauth/authorize?response_type=token&client_id=client&redirect_uri=https://www.baidu.com

###

GET http://localhost:8080/user/profile
Authorization: bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJ1c2VyIiwic2NvcGUiOlsicmVhZCJdLCJvcmdhbml6YXRpb24iOiJ1c2VydEt4QiIsImV4cCI6MTU1ODA1NzgwMCwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImp0aSI6ImY4MzhjYmI0LWQ5NDktNDAyNS1iMWFkLWVlM2ZhMTAxMDk5NSIsImNsaWVudF9pZCI6ImNsaWVudCJ9.UVE50hlr3lFrLUvJcIBo6gzNmsQPszYkAoQ-aXZykk5l9WIwuI2ZhyzjUJx0HmSVWi-q7GaUVUYEbVnnhuZ6JnJW4YGW1iyeYXirjfHufzgU9Z75dBJmAw6WufZWoL8ZTXGcommRSccdAEN54dCjYJK77izKmM_WGYHku0R_6jK-81ot0vDn3zV6LrpPA2Zq3yRffRm9SkMtyAALtDE33KFuYRlFtAAxrJs3rsumcRoQz56S9Gi5cIxGwiXqQXCTJbr5jaDXJcor1jRdzo1N-pjgLgvtCrpuxSehNk2SfVVeJ8_7hphN-Xr03HS6oxnoYmS9KJsY4FNCCssE3y9B_w

###

GET http://localhost:8082/order/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJ1c2VyIiwic2NvcGUiOlsicmVhZCJdLCJvcmdhbml6YXRpb24iOiJ1c2VyakJQWCIsImV4cCI6MTU1ODAwNzI5NiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImp0aSI6Ijc0ZjY2YjFiLTExZDAtNDkyMy1iMTU5LTRlZTUzMmNmYTU3MCIsImNsaWVudF9pZCI6ImNsaWVudCJ9.SkwNgQR_y3AEeOn3cdUpLqLxeR2ZTOWgiI2oK4iCyx0

###

GET http://localhost:8080/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJ1c2VyIiwic2NvcGUiOlsicmVhZCJdLCJvcmdhbml6YXRpb24iOiJ1c2VyV01aTyIsImV4cCI6MTU1ODAwOTM1NSwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImp0aSI6IjgwOTM5YzA4LWZkMjQtNDE1MC04YmRjLWU2OGE1M2ExMmFiNyIsImNsaWVudF9pZCI6ImNsaWVudCJ9.jdSx3Pb0IuF1HvnIlEWW7hfPsLHMZpmxwULBhJPmQZc
Authorization: Basic Y2xpZW50OjEyMzQ1Ng==

###

GET http://localhost:8080/oauth/authorize?response_type=code&client_id=client&scope=read&redirect_uri=https://www.baidu.com

###

POST http://localhost:8080/oauth/token?grant_type=authorization_code&code=8Efcrb&redirect_uri=https://www.baidu.com&scope=read
Authorization: Basic Y2xpZW50OjEyMzQ1Ng==

###

GET http://localhost:8081
Authorization: bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJ1c2VyIiwic2NvcGUiOlsicmVhZCJdLCJvcmdhbml6YXRpb24iOiJ1c2VySEJJdiIsImV4cCI6MTU1ODA2MzkzMiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImp0aSI6IjJhN2VmMmUzLWMxMjYtNDFkMy05ZWZhLWY5NDMwZGJiZTU5ZSIsImNsaWVudF9pZCI6ImNsaWVudCJ9.NXJD0yMPpTk82Hc5PDxIsyikCs565-EB8cL481GVGRMoCBMl3u6sfAflAfd8lIRcFJqQEEKjIkyXp2xcj9H3y14PuHlTOwSYvX-D6gaPLYTR8fCgoewVF8vzQqFXEhwP5YFQlnAUuefgRWs5wWFlVhspcrXD-aZvPGXYMoVplbEQrgMClJkzCsQZ5IEJass59RrdAcZiwO3c_ETp20LV9Sb6za9ybw0Z-VhbAEbJnf8kuBdrho87qCRiR5vkOO3X6cqgVo6LAeKo4Z0XK9J6AZ3uZI3HxzesEgVtjcEHhr9CqG9DhMrbW7l27y5Ngrn0eWzZXLGYfgMF0patQtP74A

###