# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8081/oauth/token?grant_type=client_credentials&scope=all&client_id=client_1&client_secret=123456

###



POST http://localhost:8081/oauth/token?grant_type=password&username=user_1&password=123456&scope=all&client_id=client_1&client_secret=123456




###
GET http://localhost:8081/oauth/authorize?response_type=code&client_id=client_1&scope=all&redirect_uri=http://localhost:8081/product/1

###
POST http://localhost:8081/oauth/token?client_id=client_1&grant_type=authorization_code&redirect_uri=http://localhost:8081/product/1&client_secret=123456&code=AWNxoJ

###



GET http://localhost:8081/product/1?access_token=89df3dec-5868-42ef-8c51-917542250ffa

###

GET http://127.0.0.1:8082/api/userinfo?access_token=06a6217d-1732-4a03-a3eb-8cb719f67292

###
