# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8081/oauth/token?grant_type=client_credentials&scope=all&client_id=client_1&client_secret=123456

###

POST http://localhost:8081/oauth/token?grant_type=password&username=user_1&password=123456&scope=all&client_id=client_1&client_secret=123456

###

GET http://localhost:8081/order/1?access_token=9293b90a-2a20-4697-a3ed-43af33692d78

###
