spring:
  datasource:
    druid:
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/learn?useSSl=false
        password: root
        username: root
      slave:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/learn?useSSl=false
        password: root
        username: root
mybatis:
  type-aliases-package: com.fengxuechao.examples.rwdb.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30