server:
  port: 8004

eureka:
  client:
    serviceUrl:
#      defaultZone: http://jackie:123456@alpha-eureka-01:8761/eureka/,http://jackie:123456@alpha-eureka-02:8762/eureka/,http://jackie:123456@alpha-eureka-03:8763/eureka/
      defaultZone: http://127.0.0.1:8761/eureka/

spring:
  application:
    name: oauth-gate-zuul

  # 添加代理头
zuul:
  add-proxy-headers: true

security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: client_1
      client-secret: 123456
      grant-type: client_credentials
      access-token-uri: /auth-server/oauth/token
      scope: all
    resource:
      loadBalanced: true
      user-info-uri: /auth-server/user/me
      prefer-token-info: false
