server:
  port: 8090
spring:
  application:
    name: say-hello
eureka:
  client:
    service-url:
      defaultZone: http://jackie:123456@alpha-eureka-01:8761/eureka/,http://jackie:123456@alpha-eureka-02:8762/eureka/,http://jackie:123456@alpha-eureka-03:8763/eureka/

