# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:8080/oauth/token?grant_type=client_credentials&scope=read
Authorization: Basic Y2xpZW50OjEyMzQ1Ng==

###

POST http://localhost:8080/oauth/token?grant_type=password&scope=read&username=user&password=123456
Authorization: Basic Y2xpZW50OjEyMzQ1Ng==

###

POST http://localhost:8080/oauth/authorize?response_type=token&client_id=client&redirect_uri=https://www.baidu.com

###

GET http://localhost:8080/user/profile
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJ1c2VyIiwic2NvcGUiOlsicmVhZCJdLCJvcmdhbml6YXRpb24iOiJ1c2VyakJQWCIsImV4cCI6MTU1ODAwNzI5NiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImp0aSI6Ijc0ZjY2YjFiLTExZDAtNDkyMy1iMTU5LTRlZTUzMmNmYTU3MCIsImNsaWVudF9pZCI6ImNsaWVudCJ9.SkwNgQR_y3AEeOn3cdUpLqLxeR2ZTOWgiI2oK4iCyx0

###

GET http://localhost:8080/order/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJ1c2VyIiwic2NvcGUiOlsicmVhZCJdLCJvcmdhbml6YXRpb24iOiJ1c2VyakJQWCIsImV4cCI6MTU1ODAwNzI5NiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImp0aSI6Ijc0ZjY2YjFiLTExZDAtNDkyMy1iMTU5LTRlZTUzMmNmYTU3MCIsImNsaWVudF9pZCI6ImNsaWVudCJ9.SkwNgQR_y3AEeOn3cdUpLqLxeR2ZTOWgiI2oK4iCyx0

###

GET http://localhost:8080/oauth/check_token?token=61322240-76d1-4427-9b12-559bb696caef
Authorization: Basic Y2xpZW50OjEyMzQ1Ng==

###

GET http://localhost:8080/oauth/authorize?response_type=code&client_id=client&scope=read&redirect_uri=https://www.baidu.com

###

POST http://localhost:8080/oauth/token?grant_type=authorization_code&code=8Efcrb&redirect_uri=https://www.baidu.com&scope=read
Authorization: Basic Y2xpZW50OjEyMzQ1Ng==

###