# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:8080/oauth/token?grant_type=client_credentials&scope=read
Authorization: Basic Y2xpZW50OjEyMzQ1Ng==

###

POST http://localhost:8080/oauth/token?grant_type=password&scope=read&username=user&password=123456
Authorization: Basic Y2xpZW50OjEyMzQ1Ng==

###

GET http://localhost:8080/user/profile?access_token=684d7346-a219-41f5-b621-b897b9e1a189

###

GET http://localhost:8080/h2-console

###